FROM node:24.18.0-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd AS build-stage

WORKDIR /app
RUN npm install --global npm@11.16.0

COPY package.json package-lock.json ./
COPY front-end/package.json ./front-end/package.json
COPY back-end/package.json ./back-end/package.json
RUN CYPRESS_INSTALL_BINARY=0 PUPPETEER_SKIP_DOWNLOAD=true \
	npm ci --include=optional --strict-allow-scripts

COPY . .
ARG CS_RELEASE_VERSION=2.7.110
ARG SOURCE_REVISION=unknown
ARG VITE_CLASSROOM_PRIVACY_APPROVED=false
ARG VITE_CLASSROOM_PRIVACY_OPERATOR_NOTICE=
ARG VITE_CLASSROOM_SERVICE_PROVIDER_NOTICE=
ARG VITE_CLASSROOM_USAGE_ENABLED=false
ARG VITE_SCHOOL_PRIVACY_CONTACT=
ARG VITE_STUDENT_ACCOUNTS_ENABLED=false
ARG VITE_STUDENT_OAUTH_ENABLED=false
ARG VITE_STUDENT_RECORD_RETENTION_DAYS=
ENV CS_RELEASE_VERSION=$CS_RELEASE_VERSION
ENV SOURCE_REVISION=$SOURCE_REVISION
ENV VITE_CLASSROOM_PRIVACY_APPROVED=$VITE_CLASSROOM_PRIVACY_APPROVED
ENV VITE_CLASSROOM_PRIVACY_OPERATOR_NOTICE=$VITE_CLASSROOM_PRIVACY_OPERATOR_NOTICE
ENV VITE_CLASSROOM_SERVICE_PROVIDER_NOTICE=$VITE_CLASSROOM_SERVICE_PROVIDER_NOTICE
ENV VITE_CLASSROOM_USAGE_ENABLED=$VITE_CLASSROOM_USAGE_ENABLED
ENV VITE_SCHOOL_PRIVACY_CONTACT=$VITE_SCHOOL_PRIVACY_CONTACT
ENV VITE_STUDENT_ACCOUNTS_ENABLED=$VITE_STUDENT_ACCOUNTS_ENABLED
ENV VITE_STUDENT_OAUTH_ENABLED=$VITE_STUDENT_OAUTH_ENABLED
ENV VITE_STUDENT_RECORD_RETENTION_DAYS=$VITE_STUDENT_RECORD_RETENTION_DAYS
RUN npm run -w front-end build

FROM nginxinc/nginx-unprivileged:stable-alpine@sha256:44e36330f74d4f3a1d4e222acca9e23b401fb87811a7597024502bb759c4dd49 AS production-stage

COPY --from=build-stage /app/front-end/dist /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
	CMD wget -q -O - http://127.0.0.1:8080/ >/dev/null || exit 1

CMD ["nginx", "-g", "daemon off;"]
