/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManagement: typeof import('./components/AccountManagement.vue')['default']
    AccountSecurity: typeof import('./components/AccountSecurity.vue')['default']
    ClassroomAnalytics: typeof import('./components/ClassroomAnalytics.vue')['default']
    CodeIdeWorkspace: typeof import('./components/CodeIdeWorkspace.vue')['default']
    CodePreview: typeof import('./components/CodePreview.vue')['default']
    CometHopperGame: typeof import('./components/games/CometHopperGame.vue')['default']
    CourseAssetPreview: typeof import('./components/CourseAssetPreview.vue')['default']
    CourseExplorer: typeof import('./components/CourseExplorer.vue')['default']
    CrosswalkCrittersGame: typeof import('./components/games/CrosswalkCrittersGame.vue')['default']
    GameCardThumbnail: typeof import('./components/games/GameCardThumbnail.vue')['default']
    LazyMarkdownContent: typeof import('./components/LazyMarkdownContent.vue')['default']
    MachineWorkshopGame: typeof import('./components/games/MachineWorkshopGame.vue')['default']
    PondPaddlersAdmin: typeof import('./components/PondPaddlersAdmin.vue')['default']
    PondPaddlersGame: typeof import('./components/PondPaddlersGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentAccess: typeof import('./components/StudentAccess.vue')['default']
    StudentManagement: typeof import('./components/StudentManagement.vue')['default']
    StudentProjectReview: typeof import('./components/StudentProjectReview.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
